### PR TITLE
Reorganize and expand session validators documentation

### PR DESCRIPTION
**Pull request by froschdesign**
The "Session Validators" section in the documentation has been restructured. All validators now have separate files and corresponding navigation links in the sidebar. An introduction file has been added with a brief on what the session validators are. The old 'validator.md' file has been deleted and its content redistributed amongst the newly created files. A redirect has been implemented from the old page to the new 'Introduction' page to maintain backwards compatibility.

### CODE REVIEW

**Review by gsteel — APPROVED** [review]
Nice 👌

Mkdocs just needs a trailing new line

**Comment by gsteel** [comment]
I'll rebase #86 when you're done here

**Comment by froschdesign** [comment]
> Mkdocs just needs a trailing new line

Added.

**Comment by froschdesign** [comment]
> I'll rebase #86 when you're done here

That was the idea. 😃

**Pull request merged**
